alachua-civicclerk:
  last_updated: '2026-02-03T15:40:03.208791'
  url_pattern: https://alachuafl.portal.civicclerk.com/event/{id}/files
  event_ids:
  - 580
  - 583
  - 584
  - 585
  - 586
  - 592
  - 593
  - 594
  - 595
  - 596
  - 597
  - 598
  - 620
  - 621
  - 622
  - 623
  - 626
  - 627
  - 628
  - 629
  - 630
  - 631
  - 632
  - 636
  - 637
  - 638
  - 641
  - 665
  - 667
  - 669
  - 673
  - 705
  - 706
  - 707
  - 708
  - 709
  - 710
  - 711
  - 723
  - 727
  - 731
  - 733
  - 734
  - 735
  - 736
  - 737
  - 738
  - 739
  - 751
  - 763
  - 764
  - 775
  - 776
  - 777
  - 778
  - 779
  - 780
  - 781
  - 782
  - 783
  - 785
  - 786
  - 787
  - 788
  - 789
  - 791
  - 795
  - 798
  - 801
  - 810
  - 812
  - 818
  - 819
  - 820
  - 822
  - 826
  - 832
  - 833
  - 834
  - 835
  - 836
  - 837
  - 838
  - 839
  - 840
  - 841
  - 842
  - 843
  - 846
  - 847
  - 848
  - 849
  - 850
  - 852
  - 853
  - 854
  - 855
  - 856
  - 857
  - 858
  - 859
  - 860
  - 861
  - 862
  - 863
  - 864
  - 865
  - 866
  - 867
  - 868
  - 869
  - 870
  - 871
  - 872
  - 873
  - 875
florida-public-notices:
  last_updated: '2026-02-02T13:47:17.459169'
  base_url: https://floridapublicnotices.com/
  archive_url: https://floridapublicnotices.com/search/archived-notices
  notice_ids:
  - fpn-0002
  - fpn-0003
  - fpn-0001
srwmd-applications:
  last_updated: '2026-02-04T19:11:18.682498'
  base_url: https://www.mysuwanneeriver.com/1616/Notice-of-Receipt-of-Applications
  document_pattern: https://www.mysuwanneeriver.com/ImageRepository/Document?documentID={id}
  document_ids:
  - 15266
  - 15268
  - 15269
  - 17942
  - 13351
  - 15263
  permit_ids:
  - 253435-2
  - 253433-4
  - 253434-3
  - 253436-1
srwmd-issuances:
  last_updated: '2026-02-05T15:24:31.056753'
  base_url: https://www.mysuwanneeriver.com/1617/Notice-of-Permit-Issuance
  document_pattern: https://www.mysuwanneeriver.com/ImageRepository/Document?documentID={id}
  document_ids:
  - 15266
  - 15268
  - 15269
  - 17942
  - 13351
  permit_ids:
  - 253400-1
  - 253399-2
  - 253398-3
srwmd-epermitting:
  last_updated: '2026-02-02T10:48:26'
  base_url: https://permitting.sjrwmd.com/srep/#/ep
  permit_pattern: https://permitting.sjrwmd.com/srep/#/ep/permit/{permit_number}
  permit_numbers: []
